application: nsfails
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /static
  static_dir: static

- url: /admin-x|/admin-x/.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
